export * from './TTranslations';
export * from './TAppEnv';
export * from './TPosition';
export * from './TSize';
export * from './TCanvasSize';
export * from './IDrawImageOnCanvasViewModel';
export * from './TDotsRef';
export * from './EDotsNames';
export * from './TResizeDots';
